services:
  web:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DEBUG=0

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "8000:8000"
    depends_on:
      - web